### ISSUE TITLE
ModuleNotFoundError: No module named 'face_alignment'

### ISSUE THREAD

**Issue by margo2130** [tanshuai0219/EDTalk#39]
hi, when i click on submit button, it give me this: 

croping pose_video
Traceback (most recent call last):
  File "data_preprocess/crop_video.py", line 1, in <module>
    import face_alignment
ModuleNotFoundError: No module named 'face_alignment'
File not found: test_data\crop_resample_pose_source1.mp4

where can i get that :
ModuleNotFoundError: No module named '**face_alignment**'?

**Comment by tanshuai0219** [comment]
> hi, when i click on submit button, it give me this:
> 
> croping pose_video Traceback (most recent call last): File "data_preprocess/crop_video.py", line 1, in import face_alignment ModuleNotFoundError: No module named 'face_alignment' File not found: test_data\crop_resample_pose_source1.mp4
> 
> where can i get that : ModuleNotFoundError: No module named '**face_alignment**'?

Please first install [face-alignment](https://github.com/1adrianb/face-alignment) by `pip install face-alignment`
