### ISSUE TITLE
 No module named 'cv2'

### ISSUE THREAD

**Issue by margo2130** [tanshuai0219/EDTalk#40]
how can i solve these errors:

 No module named 'cv2'
 No module named 'dlib'

**Comment by margo2130** [comment]
> try this after activating virtual environment
> 
> pip install wheel
> 
> and then
> 
> pip install dlib

thanks.
but it didn't solve. that error still is.

```
(venv) C:\Users\Hadi.M\Desktop\AI\Ed Talk\EDTalk-main>pip install dlib
Collecting dlib
  Using cached dlib-19.24.6.tar.gz (3.4 MB)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Hadi.M\AppData\Local\Temp\pip-wheel-e964qiyz'
       cwd: C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\
  Complete output (51 lines):
  running bdist_wheel
  running build
  running build_ext
  Building extension for Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\build\lib.win-amd64-3.8 -DPYTHON_EXECUTABLE=c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\scripts\python.exe -DDLIB_USE_FFMPEG=OFF -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\build\lib.win-amd64-3.8 -A x64'
  -- Building for: Visual Studio 17 2022
  -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
  -- The C compiler identification is unknown
  -- The CXX compiler identification is unknown
  CMake Error at CMakeLists.txt:14 (project):
    No CMAKE_C_COMPILER could be found.



  CMake Error at CMakeLists.txt:14 (project):
    No CMAKE_CXX_COMPILER could be found.



  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\setup.py", line 243, in <module>
      setup(
    File "c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\lib\site-packages\wheel\_bdist_wheel.py", line 378, in run
      self.run_command("build")
    File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\setup.py", line 168, in run
      self.build_extension(ext)
    File "C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\setup.py", line 206, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\build\\lib.win-amd64-3.8', '-DPYTHON_EXECUTABLE=c:\\users\\hadi.m\\desktop\\ai\\ed talk\\edtalk-main\\venv\\scripts\\python.exe', '-DDLIB_USE_FFMPEG=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\build\\lib.win-amd64-3.8', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Hadi.M\AppData\Local\Temp\pip-record-q6tzangy\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\include\site\python3.8\dlib'
         cwd: C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\
    Complete output (53 lines):
    running install
    running build
    running build_ext
    Building extension for Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
    Invoking CMake setup: 'cmake C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\build\lib.win-amd64-3.8 -DPYTHON_EXECUTABLE=c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\scripts\python.exe -DDLIB_USE_FFMPEG=OFF -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\build\lib.win-amd64-3.8 -A x64'
    -- Building for: Visual Studio 17 2022
    -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
    -- The C compiler identification is unknown
    -- The CXX compiler identification is unknown
    CMake Error at CMakeLists.txt:14 (project):
      No CMAKE_C_COMPILER could be found.



    CMake Error at CMakeLists.txt:14 (project):
      No CMAKE_CXX_COMPILER could be found.



    -- Configuring incomplete, errors occurred!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\setup.py", line 243, in <module>
        setup(
      File "c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\setup.py", line 168, in run
        self.build_extension(ext)
      File "C:\Users\Hadi.M\AppData\Local\Temp\pip-install-h1j77r9s\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\setup.py", line 206, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "C:\Users\Hadi.M\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\build\\lib.win-amd64-3.8', '-DPYTHON_EXECUTABLE=c:\\users\\hadi.m\\desktop\\ai\\ed talk\\edtalk-main\\venv\\scripts\\python.exe', '-DDLIB_USE_FFMPEG=OFF', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\build\\lib.win-amd64-3.8', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Hadi.M\\AppData\\Local\\Temp\\pip-install-h1j77r9s\\dlib_5ed97b3a3b7442b5ae0ff11b76fe9f5f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Hadi.M\AppData\Local\Temp\pip-record-q6tzangy\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\include\site\python3.8\dlib' Check the logs for full command output.
WARNING: You are using pip version 21.1.1; however, version 24.2 is available.
You should consider upgrading via the 'c:\users\hadi.m\desktop\ai\ed talk\edtalk-main\venv\scripts\python.exe -m pip install --upgrade pip' command.

(venv) C:\Users\Hadi.M\Desktop\AI\Ed Talk\EDTalk-main>
```

**Comment by nitinmukesh** [comment]
It seems CMAKE is not installed

refer Step0 to check if CMAKE is installed, if not see the end section
https://drive.google.com/file/d/1b_DcDQJnGjDr6eoaajbWi2uUjM3mbe5e/view?usp=sharing

**Comment by margo2130** [comment]
> It seems CMAKE is not installed
> 
> refer Step0 to check if CMAKE is installed, if not see the end section on how to install https://drive.google.com/file/d/1b_DcDQJnGjDr6eoaajbWi2uUjM3mbe5e/view?usp=sharing

thanks. i installed it. btw i enter the code and say this:

`C:\Users\Hadi.M>cmake --help
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Options
  -S <path-to-source>          = Explicitly specify a source directory.
  -B <path-to-build>           = Explicitly specify a build directory.
  -C <initial-cache>           = Pre-load a script to populate the cache.
  -D <var>[:<type>]=<value>    = Create or update a cmake cache entry.
  -U <globbing_expr>           = Remove matching entries from CMake cache.
  -G <generator-name>          = Specify a build system generator.
  -T <toolset-name>            = Specify toolset name if supported by
                                 generator.
  -A <platform-name>           = Specify platform name if supported by
                                 generator.
  --toolchain <file>           = Specify toolchain file
                                 [CMAKE_TOOLCHAIN_FILE].
  --install-prefix <directory> = Specify install directory
                                 [CMAKE_INSTALL_PREFIX].
  -Wdev                        = Enable developer warnings.
  -Wno-dev                     = Suppress developer warnings.
  -Werror=dev                  = Make developer warnings errors.
  -Wno-error=dev               = Make developer warnings not errors.
  -Wdeprecated                 = Enable deprecation warnings.
  -Wno-deprecated              = Suppress deprecation warnings.
  -Werror=deprecated           = Make deprecated macro and function warnings
                                 errors.
  -Wno-error=deprecated        = Make deprecated macro and function warnings
                                 not errors.
  --preset <preset>,--preset=<preset>
                               = Specify a configure preset.
  --list-presets[=<type>]      = List available presets.
  -E                           = CMake command mode.
  -L[A][H]                     = List non-advanced cached variables.
  --fresh                      = Configure a fresh build tree, removing any
                                 existing cache file.
  --build <dir>                = Build a CMake-generated project binary tree.
  --install <dir>              = Install a CMake-generated project binary
                                 tree.
  --open <dir>                 = Open generated project in the associated
                                 application.
  -N                           = View mode only.
  -P <file>                    = Process script mode.
  --find-package               = Legacy pkg-config like mode.  Do not use.
  --graphviz=<file>            = Generate graphviz of dependencies, see
                                 CMakeGraphVizOptions.cmake for more.
  --system-information [file]  = Dump information about this system.
  --log-level=<ERROR|WARNING|NOTICE|STATUS|VERBOSE|DEBUG|TRACE>
                               = Set the verbosity of messages from CMake
                                 files.  --loglevel is also accepted for
                                 backward compatibility reasons.
  --log-context                = Prepend log messages with context, if given
  --debug-trycompile           = Do not delete the try_compile build tree.
                                 Only useful on one try_compile at a time.
  --debug-output               = Put cmake in a debug mode.
  --debug-find                 = Put cmake find in a debug mode.
  --debug-find-pkg=<pkg-name>[,...]
                               = Limit cmake debug-find to the
                                 comma-separated list of packages
  --debug-find-var=<var-name>[,...]
                               = Limit cmake debug-find to the
                                 comma-separated list of result variables
  --trace                      = Put cmake in trace mode.
  --trace-expand               = Put cmake in trace mode with variable
                                 expansion.
  --trace-format=<human|json-v1>
                               = Set the output format of the trace.
  --trace-source=<file>        = Trace only this CMake file/module.  Multiple
                                 options allowed.
  --trace-redirect=<file>      = Redirect trace output to a file instead of
                                 stderr.
  --warn-uninitialized         = Warn about uninitialized values.
  --no-warn-unused-cli         = Don't warn about command line options.
  --check-system-vars          = Find problems with variable usage in system
                                 files.
  --compile-no-warning-as-error= Ignore COMPILE_WARNING_AS_ERROR property and
                                 CMAKE_COMPILE_WARNING_AS_ERROR variable.
  --profiling-format=<fmt>     = Output data for profiling CMake scripts.
                                 Supported formats: google-trace
  --profiling-output=<file>    = Select an output path for the profiling data
                                 enabled through --profiling-format.
  -h,-H,--help,-help,-usage,/? = Print usage information and exit.
  --version,-version,/V [<file>]
                               = Print version number and exit.
  --help <keyword> [<file>]    = Print help for one keyword and exit.
  --help-full [<file>]         = Print all help manuals and exit.
  --help-manual <man> [<file>] = Print one help manual and exit.
  --help-manual-list [<file>]  = List help manuals available and exit.
  --help-command <cmd> [<file>]= Print help for one command and exit.
  --help-command-list [<file>] = List commands with help available and exit.
  --help-commands [<file>]     = Print cmake-commands manual and exit.
  --help-module <mod> [<file>] = Print help for one module and exit.
  --help-module-list [<file>]  = List modules with help available and exit.
  --help-modules [<file>]      = Print cmake-modules manual and exit.
  --help-policy <cmp> [<file>] = Print help for one policy and exit.
  --help-policy-list [<file>]  = List policies with help available and exit.
  --help-policies [<file>]     = Print cmake-policies manual and exit.
  --help-property <prop> [<file>]
                               = Print help for one property and exit.
  --help-property-list [<file>]= List properties with help available and
                                 exit.
  --help-properties [<file>]   = Print cmake-properties manual and exit.
  --help-variable var [<file>] = Print help for one variable and exit.
  --help-variable-list [<file>]= List variables with help available and exit.
  --help-variables [<file>]    = Print cmake-variables manual and exit.

Generators

The following generators are available on this platform (* marks default):
* Visual Studio 17 2022        = Generates Visual Studio 2022 project files.
                                 Use -A option to specify architecture.
  Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Deprecated.  Generates Visual Studio 2013
                                 project files.  Optional [arch] can be
                                 "Win64" or "ARM".
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.
  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - NMake Makefiles JOM
                               = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - Ninja           = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files
                                 (deprecated).
  CodeLite - MinGW Makefiles   = Generates CodeLite project files
                                 (deprecated).
  CodeLite - NMake Makefiles   = Generates CodeLite project files
                                 (deprecated).
  CodeLite - Ninja             = Generates CodeLite project files
                                 (deprecated).
  CodeLite - Unix Makefiles    = Generates CodeLite project files
                                 (deprecated).
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Kate - MinGW Makefiles       = Generates Kate project files (deprecated).
  Kate - NMake Makefiles       = Generates Kate project files (deprecated).
  Kate - Ninja                 = Generates Kate project files (deprecated).
  Kate - Ninja Multi-Config    = Generates Kate project files (deprecated).
  Kate - Unix Makefiles        = Generates Kate project files (deprecated).
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).


C:\Users\Hadi.M>`

**Comment by margo2130** [comment]
well i installed it but when i tick "crop" button, it say 
==> loading data
No module named 'dlib'
------------
i couldn't use this project. maybe i should go for another project.
if anyone has the answer for this problem, say it for others.
thank you.

**Comment by abozahran** [comment]
FIRST ACTIVATE CONDA

conda activate EDTALK
conda install -c conda-forge opencv
pip install opencv-python
pip install dlib
