### ISSUE TITLE
关于 No module named 'face_alignment' 的问题

### ISSUE THREAD

**Issue by wangaocheng** [tanshuai0219/EDTalk#43]
首先需要安装一下 pip install face_alignment

但是 crop_video.py 里面的 84行会报错：

_==> croping pose_video
Traceback (most recent call last):
  File "data_preprocess/crop_video.py", line 84, in <module>
    fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False, device=device)
  File "E:\Env\edtalk\lib\enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D_

修改84行:
fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False, device=device)
为：
fa = face_alignment.FaceAlignment(face_alignment.LandmarksType.TWO_D, flip_input=False, device=device)

应该是作者开发的时候用了face_alignment的老版本。

**Comment by torracxiaokeai** [comment]
你好，我在执行如下代码时，
python data_preprocess/data_preprocess_for_train/extract_bbox.py

发生了如下报错，这个你遇到了吗
Traceback (most recent call last):
  File "/root/avatar_project/EDTalk/data_preprocess/data_preprocess_for_train/extract_bbox.py", line 32, in <module>
    fa = [face_detection.FaceAlignment(face_detection.LandmarksType.TWO_D, flip_input=False,
  File "/root/avatar_project/EDTalk/data_preprocess/data_preprocess_for_train/extract_bbox.py", line 32, in <listcomp>
    fa = [face_detection.FaceAlignment(face_detection.LandmarksType.TWO_D, flip_input=False,
AttributeError: module 'face_detection' has no attribute 'FaceAlignment'
