### ISSUE TITLE
'Namespace' object has no attribute 'semantic_radius'

### ISSUE THREAD

**Issue by torracxiaokeai** [tanshuai0219/EDTalk#45]
When I tried to train directly by using 
`python -m torch.distributed.launch --nproc_per_node=2 --master_port 12345 train/train_E_G.py`

There is an error
Traceback (most recent call last):
  File "/root/avatar_project/EDTalk/train/train_E_G.py", line 253, in <module>
    main(opts)
  File "/root/avatar_project/EDTalk/train/train_E_G.py", line 92, in main
    dataset = VoxDataset(args, is_inference= False, transform = transform)
  File "/root/avatar_project/EDTalk/train/datasets/dataset_MEAD_HDTF.py", line 47, in __init__
    self.semantic_radius = opt.semantic_radius
AttributeError: 'Namespace' object has no attribute 'semantic_radius'

It seems that the training parameter in `train/train_E_G.py` has no attribute  'semantic_radius', so I am confused about it .

**Comment by tanshuai0219** [comment]
> semantic_radius

Sorry for the late reply. "semantic_radius" has no use in our code, you can directly delete it.
